### ISSUE TITLE
【报错】非法 Forward node 将跳过

### ISSUE THREAD

**Issue by a930389426** [RShock/zhenxun_plugin_onimai#3]
![image](https://user-images.githubusercontent.com/59648220/215304987-f5f1d01a-774a-40f4-8d13-cd2c896bb660.png)
![image](https://user-images.githubusercontent.com/59648220/215305011-e35540d1-a535-4abf-99ba-7a131b577ff3.png)

**Comment by RShock** [comment]
初步猜想为未找到文件导致，你可以用以下方法自查：
删除或重命名src文件夹(切换为在线浏览，若已是在线浏览，就切换回本地浏览)，观看情况是否改变。

**Comment by a930389426** [comment]
> 初步猜想为未找到文件导致，你可以用以下方法自查： 删除或重命名src文件夹(切换为在线浏览，若已是在线浏览，就切换回本地浏览)，观看情况是否改变。

我删除src文件夹后，出现新的报错

**Comment by a930389426** [comment]
![image](https://user-images.githubusercontent.com/59648220/215306481-fe4e19c9-876f-4cf0-92cf-3a4a34a49f64.png)

**Comment by a930389426** [comment]
哦这个报错是我开了vpn造成的，关了vpn就行了，但是在线浏览依然不行
![image](https://user-images.githubusercontent.com/59648220/215306562-8d153e35-9bf8-4a03-8c2e-f570529e29f7.png)

**Comment by a930389426** [comment]
同样是“非法 Forward node 将跳过 ”

**Comment by RShock** [comment]
你的gocqhttp版本是rc3吗？

**Comment by a930389426** [comment]
> 你的gocqhttp版本是rc3吗？

要rc3以上才能用吗？我rc1的，现在去更新试试

**Comment by a930389426** [comment]
更新了gocqhttp版本后就可以了，谢谢

**Comment by RShock** [comment]
rc1的转发消息规范和nonebot v11不同。


另外rc1版本我遇到过一个[未解决问题](https://github.com/Mrs4s/go-cqhttp/issues/1563)，大量以组消息发图可能导致机器人崩溃，刚好本插件符合条件，最好更新（然后我就不用修了 ）
